### ISSUE TITLE
Accessory for the main zone does not respond and does not have an input list.

### ISSUE THREAD

**Issue by dloxo** [NorthernMan54/homebridge-yamaha-zone-tv#10]
Accessory for the main zone does not respond and does not have an input list.

**Here is the config json:**
         {
            "platform": "yamaha-zone-tv",
            "discovery_timeout": 30,
            "max_volume": 10,
            "zone_controllers_only_for": "Main"
        }

**Here is the relevant log portion on startup:**
[8/26/2019, 2:27:20 PM] [yamaha-zone-tv] Initializing yamaha-zone-tv platform...
[8/26/2019, 2:27:20 PM] Loading 0 accessories...
[8/26/2019, 2:27:20 PM] [yamaha-zone-tv] Getting Yamaha AVR devices.
[8/26/2019, 2:27:20 PM] [yamaha-zone-tv] Possible Yamaha device discovered nas [ 'fe80::211:32ff:fe6e:2203', '10.0.20.122' ]
[8/26/2019, 2:27:20 PM] [yamaha-zone-tv] Possible Yamaha device discovered Media Room [ '10.0.10.197' ]
[8/26/2019, 2:27:20 PM] [yamaha-zone-tv] Possible Yamaha device discovered avr [ '10.0.10.196' ]
[8/26/2019, 2:27:20 PM] [yamaha-zone-tv] Possible Yamaha device discovered sprinklers [ '10.0.10.185' ]
[8/26/2019, 2:27:20 PM] [yamaha-zone-tv] Found Yamaha RX-A2060 - 08507173, "avr"
[8/26/2019, 2:27:20 PM] [yamaha-zone-tv] Adding TV Control for Main
Unhandled rejection TypeError: Cannot read property 'inputs' of undefined
    at /homebridge/node_modules/homebridge-yamaha-zone-tv/index.js:422:87
    at tryCatcher (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:459:14)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._fulfillPromises (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:674:14)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:700:18)
    at Promise._fulfill (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)

**Here is the relevant log portion on use:**
Unhandled rejection TypeError: Cannot read property 'inputs' of undefined
    at /homebridge/node_modules/homebridge-yamaha-zone-tv/index.js:433:31
    at tryCatcher (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:459:14)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._fulfillPromises (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:674:14)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:700:18)
    at Promise._fulfill (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)

**Comment by NorthernMan54** [comment]
Can you share a DEBUG log ?  ie

DEBUG=* homebridge

It should log the details of your receiver including why it thinks your receiver has no Inputs

**Comment by dloxo** [comment]
Sorry, something else is going on with my Docker install.

**Comment by qelanhari** [comment]
I have the same issue with an A2020 : 

`
{
  "YAMAHA_AV": {
    "$": {
      "rsp": "GET",
      "RC": "0"
    },
    "Main_Zone": [
      {
        "Basic_Status": [
          {
            "Power_Control": [
              {
                "Power": [
                  "On"
                ],
                "Sleep": [
                  "Off"
                ]
              }
            ],
            "Volume": [
              {
                "Lvl": [
                  {
                    "Val": [
                      "-360"
                    ],
                    "Exp": [
                      "1"
                    ],
                    "Unit": [
                      "dB"
                    ]
                  }
                ],
                "Mute": [
                  "Off"
                ],
                "Subwoofer_Trim": [
                  {
                    "Val": [
                      "0"
                    ],
                    "Exp": [
                      "1"
                    ],
                    "Unit": [
                      "dB"
                    ]
                  }
                ]
              }
            ],
            "Input": [
              {
                "Input_Sel": [
                  "AUDIO1"
                ],
                "Input_Sel_Item_Info": [
                  {
                    "Param": [
                      "AUDIO1"
                    ],
                    "RW": [
                      "RW"
                    ],
                    "Title": [
                      "Netflix"
                    ],
                    "Icon": [
                      {
                        "On": [
                          "/YamahaRemoteControl/Icons/icon072.png"
                        ],
                        "Off": [
                          ""
                        ]
                      }
                    ],
                    "Src_Name": [
                      ""
                    ],
                    "Src_Number": [
                      "1"
                    ]
                  }
                ]
              }
            ],
            "Surround": [
              {
                "Program_Sel": [
                  {
                    "Current": [
                      {
                        "Straight": [
                          "Off"
                        ],
                        "Enhancer": [
                          "Off"
                        ],
                        "Sound_Program": [
                          "9ch Stereo"
                        ]
                      }
                    ]
                  }
                ],
                "_3D_Cinema_DSP": [
                  "Auto"
                ],
                "Enhancer_Type": [
                  "High Resolution"
                ]
              }
            ],
            "Party_Info": [
              "Off"
            ],
            "Sound_Video": [
              {
                "Tone": [
                  {
                    "Bass": [
                      {
                        "Val": [
                          "0"
                        ],
                        "Exp": [
                          "1"
                        ],
                        "Unit": [
                          "dB"
                        ]
                      }
                    ],
                    "Treble": [
                      {
                        "Val": [
                          "0"
                        ],
                        "Exp": [
                          "1"
                        ],
                        "Unit": [
                          "dB"
                        ]
                      }
                    ]
                  }
                ],
                "Pure_Direct": [
                  {
                    "Mode": [
                      "Off"
                    ]
                  }
                ],
                "HDMI": [
                  {
                    "Standby_Through_Info": [
                      "On"
                    ],
                    "Output": [
                      {
                        "OUT_1": [
                          "On"
                        ],
                        "OUT_2": [
                          "On"
                        ],
                        "OUT_2_Info": [
                          "On"
                        ]
                      }
                    ],
                    "Video": [
                      {
                        "Preset_Sel": [
                          {
                            "Current": [
                              "Preset 1"
                            ]
                          }
                        ]
                      }
                    ]
                  }
                ],
                "Adaptive_DRC": [
                  "Off"
                ],
                "Dialogue_Adjust": [
                  {
                    "Dialogue_Lift": [
                      "0"
                    ],
                    "Dialogue_Lvl": [
                      "0"
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
}

`

**Comment by qelanhari** [comment]
You're just missing a `.bind(this)` L422

**Comment by NorthernMan54** [comment]
Could you make a pull request with this, and I will publish.

I don’t have access to my receiver for a few weeks, and can’t test any changes.

**Comment by qelanhari** [comment]
Yep, I was planning to. But for now I'm trying to find out why I do not have the Speaker service to set the volume.
