### ISSUE TITLE
Yama avr3080

### ISSUE THREAD

**Issue by kinkawe** [NorthernMan54/homebridge-yamaha-zone-tv#11]
Hi,
I'm getting this error using this plugin for a yamaha avr 3080 

Sep 24 21:32:08 raspberrypi homebridge[28897]: [9/24/2019, 9:32:08 PM] [yamaha-zone-tv] Possible Yamaha device discovered HP Color LaserJet MFP M477fdw (A7BE08) [ '192.168.1.63', 'fe80::9653:30ff:fe69:73f3' ]
Sep 24 21:32:08 raspberrypi homebridge[28897]: [9/24/2019, 9:32:08 PM] [yamaha-zone-tv] Possible Yamaha device discovered RX-A3080 04FE4C [ '192.168.1.135', 'fe80::4e1b:86ff:fe04:fe4d' ]
Sep 24 21:32:09 raspberrypi homebridge[28897]: [9/24/2019, 9:32:09 PM] [yamaha-zone-tv] Found Yamaha RX-A3080 - 0EBAF593, "RX-A3080 04FE4C"
Sep 24 21:32:10 raspberrypi homebridge[28897]: [9/24/2019, 9:32:10 PM] [yamaha-zone-tv] Adding TV Control for Main
Sep 24 21:32:10 raspberrypi homebridge[28897]: [9/24/2019, 9:32:10 PM] [yamaha-zone-tv] Adding TV Control for Zone2
Sep 24 21:32:10 raspberrypi homebridge[28897]: [9/24/2019, 9:32:10 PM] [yamaha-zone-tv] Adding TV Control for Zone3
Sep 24 21:32:10 raspberrypi homebridge[28897]: Unhandled rejection TypeError: Cannot read property 'inputs' of undefined
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at /usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:423:87
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/util.js:16:23)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:517:31)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:459:14)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:674:14)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:700:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]: Unhandled rejection TypeError: Cannot read property 'inputs' of undefined
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at /usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:423:87
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/util.js:16:23)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:517:31)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
Sep 24 21:32:10 raspberrypi homebridge[28897]:     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
Sep 24 21:32:11 raspberrypi homebridge[28897]:     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
Sep 24 21:32:11 raspberrypi homebridge[28897]:     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:459:14)
Sep 24 21:32:11 raspberrypi homebridge[28897]:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
Sep 24 21:32:11 raspberrypi homebridge[28897]:     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
Sep 24 21:32:11 raspberrypi homebridge[28897]:     at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:674:14)
Sep 24 21:32:11 raspberrypi homebridge[28897]:     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:700:18)
Sep 24 21:32:11 raspberrypi homebridge[28897]:     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
Sep 24 21:32:11 raspberrypi homebridge[28897]:     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
Sep 24 21:32:11 raspberrypi homebridge[28897]:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
Sep 24 21:32:11 raspberrypi homebridge[28897]:     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
S

**Comment by NorthernMan54** [comment]
I created a fix for what I think the issue is, but I don’t know for sure as I don’t have access to my receiver now.  Can you update to the latest, and try again.

If it still has issues, please include a DEBUG log as well this time as it will give more details.

Tks

**Comment by kinkawe** [comment]
Hi,
Thanks for looking into this.  See the debug log attached.

[homebridge_upload.debug.txt](https://github.com/NorthernMan54/homebridge-yamaha-zone-tv/files/3663834/homebridge_upload.debug.txt)

**Comment by NorthernMan54** [comment]
I'm just heading out on a vacation, and won't be back for about 3 weeks.  One question though, does the plugin still work with the error?

**Comment by kinkawe** [comment]
No - unfortunately.  Have a great break!

**Comment by kinkawe** [comment]
Hi - thanks!  I've updated and the errors are gone.  Still testing and will let you know if all is sorted.

**Comment by kinkawe** [comment]
Hi - not had any issues since the fix went in.  Many thanks for resolving!
