### ISSUE TITLE
No Response

### ISSUE THREAD

**Issue by moibensa** [NorthernMan54/homebridge-yamaha-zone-tv#12]
I’ve been using this plugin for a while now without any problems. I recently updated homebridge and all of my plugins. Had to end up removing homebridge entirely and setting it up from scratch. I got everything to work except this plugin. I’ve removed it and added it again over and over changing homebridge username, restarting homebridge, removing persist and accessories folders- nothing works. All I get is “no response”.

Also on a side note, I’ve always had an issue with my Yamaha receiver bc it only allows short names for each zone. So I’ve always had to give zones a shorter name that I’d like to. On setting up homebridge-Yamaha-zone-tv I could change it to what I wanted to, but whenever I restart homebridge I have to change the name all over again... It’d be great to be able to preset the names of zones. But as much as I would like that feature I need to at least be able to use it...

**Comment by moibensa** [comment]
Here’s the err log:
Mon, 07 Oct 2019 01:17:02 GMT Accessory [LivingY] Setting Characteristic "Active" to value 1
2019-10-07T01:17:02.833Z yamaha-zone-tv setActive Main_Zone 1
Mon, 07 Oct 2019 01:17:02 GMT Accessory [LivingY] Setting Characteristic "Active Identifier" to value 2
2019-10-07T01:17:02.838Z yamaha-zone-tv setActiveIdentifier => setNewValue:  Main_Zone 2
[10/6/2019, 9:17:02 PM] TypeError: Cannot read property 'find' of undefined
    at Characteristic.ActiveIdentifier.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:441:39)
    at Characteristic.ActiveIdentifier.emit (events.js:198:13)
    at Characteristic.ActiveIdentifier.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:198:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:198:13)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Mon, 07 Oct 2019 01:17:04 GMT Yamaha-nodejs getBasicInfo Main_Zone {

And then it just lists the Json with all the info of that zone and after:

Mon, 07 Oct 2019 01:17:07 GMT EventedHTTPServer [::ffff:10.128.128.103] Client connection closed
Mon, 07 Oct 2019 01:17:07 GMT EventedHTTPServer [::ffff:10.128.128.103] HTTP connection was closed
Mon, 07 Oct 2019 01:17:07 GMT EventedHTTPServer [::ffff:10.128.128.103] HTTP server was closed

**Comment by moibensa** [comment]
And this happens when I force touch on the zone:
![A6858290-77C4-4A66-9689-3C170D4D206E](https://user-images.githubusercontent.com/29363115/66279952-4b67d800-e882-11e9-89cb-61909b967e80.jpeg)

**Comment by NorthernMan54** [comment]
Okay, let me take a look at this

**Comment by NorthernMan54** [comment]
This should now be resolved, please update and try again
