### ISSUE TITLE
Party mode switch is not working + error

### ISSUE THREAD

**Issue by nitaybz** [NorthernMan54/homebridge-yamaha-zone-tv#18]
Hey, thanks for this awesome plugin!
first of all I wonder if it's possible to remove party mode, not sure what it does and I really want to remove it as it don't work and return the following error in the logs:

```
Jul 22 21:30:53 raspberrypi homebridge[15727]: Unhandled rejection TypeError: Cannot read property '0' of undefined
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Object.basicStatus.isPartyModeEnabled (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/yamaha-nodejs/simpleCommands.js:388:73)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at /usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/yamaha-nodejs/simpleCommands.js:474:37
Jul 22 21:30:53 raspberrypi homebridge[15727]: at tryCatcher (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/util.js:16:23)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:547:31)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:604:18)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:649:10)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:729:18)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:673:18)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:466:57)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:559:17)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:604:18)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:649:10)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:729:18)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:673:18)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:489:14)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:559:17)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:604:18)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._fulfillPromises (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:704:14)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:730:18)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:673:18)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:466:57)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:559:17)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:604:18)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:649:10)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:729:18)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:673:18)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:466:57)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:559:17)
Jul 22 21:30:53 raspberrypi homebridge[15727]: at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:604:18)
Jul 22 21:30:54 raspberrypi homebridge[15727]: at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:649:10)
Jul 22 21:30:54 raspberrypi homebridge[15727]: at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:729:18)
Jul 22 21:30:54 raspberrypi homebridge[15727]: at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:673:18)
Jul 22 21:30:54 raspberrypi homebridge[15727]: at Timeout._onTimeout (/usr/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/timers.js:26:46)
Jul 22 21:30:54 raspberrypi homebridge[15727]: at listOnTimeout (internal/timers.js:535:17)

```

Please assist

**Comment by NorthernMan54** [comment]
In my receiver ‘Party Mode’ sets all zones to the same input, and enables all speakers.   I guess yours doesn’t support it.

Let me see what I can do to stop the issue or make the party mode an option.

**Comment by nitaybz** [comment]
Thanks for the positive response :)
Do you need a PR from me? Also I noticed a few other small bugs, I'll open a different issue for that.

**Comment by NorthernMan54** [comment]
A PR is great
