### ISSUE TITLE
Homebridge 2.0 Support

### ISSUE THREAD

**Issue by Quickstep3** [NorthernMan54/homebridge-yamaha-zone-tv#30]
### Analysis

Plugin appears to have issues running under Homerbidge 2.0 (beta 15) due to deprecated features in HAP?

### Expected Behavior

Plugin is updated to support Homebridge 2.0.

### Steps To Reproduce

Install Homebridge 2.0 Beta 15+ with plugin running

### Logs

```markdown
[02/09/2024, 20:27:30] [yamaha-zone-tv] Child bridge starting (pid 1271)...
[02/09/2024, 20:27:31] Registering platform 'homebridge-yamaha-zone-tv.yamaha-zone-tv'
[02/09/2024, 20:27:31] [yamaha-zone-tv] Child bridge started successfully (plugin v0.1.23).
HAP-NodeJS WARNING: The accessory 'yamaha-zone-tv' has an invalid 'Name' characteristic ('yamaha-zone-tv'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
[02/09/2024, 20:27:31] Loaded 0 cached accessories from cachedAccessories.0E8EA9044C31.
HAP-NodeJS WARNING: The accessory 'yamaha-zone-tv FCBC' has an invalid 'Name' characteristic ('yamaha-zone-tv FCBC'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
[02/09/2024, 20:27:31] [yamaha-zone-tv] Getting Yamaha AVR devices.
[02/09/2024, 20:27:31] Homebridge v2.0.0-beta.15 (HAP v1.1.1-beta.2) (yamaha-zone-tv) is running on port 42868.
[02/09/2024, 20:27:31] [yamaha-zone-tv] Possible Yamaha device discovered Linksys00754 [ '192.168.1.183' ]
[02/09/2024, 20:27:31] [yamaha-zone-tv] Possible Yamaha device discovered Linksys00434 [ '192.168.1.67' ]
[02/09/2024, 20:27:31] [yamaha-zone-tv] Possible Yamaha device discovered Linksys00419 [ '192.168.1.238' ]
[02/09/2024, 20:27:31] [yamaha-zone-tv] Possible Yamaha device discovered Living Room Amplifier [ '192.168.1.169' ]
[02/09/2024, 20:27:31] [yamaha-zone-tv] Possible Yamaha device discovered Rumba [ 'fe80::211:32ff:fe15:859e', '192.168.1.125' ]
[02/09/2024, 20:27:31] [yamaha-zone-tv] Possible Yamaha device discovered Linksys00837 [ '192.168.1.36' ]
[02/09/2024, 20:27:31] [yamaha-zone-tv] Possible Yamaha device discovered myrouter [ '192.168.1.1' ]
[02/09/2024, 20:27:31] [yamaha-zone-tv] Found Yamaha RX-V681 - 071D7FA3, "Living Room Amplifier"
[02/09/2024, 20:27:31] [yamaha-zone-tv] Possible Yamaha device discovered LaserPrinter [ '192.168.1.217', 'fe80::32cd:a7ff:fe1e:25b8' ]
[02/09/2024, 20:27:31] [yamaha-zone-tv] DEBUG: Failed getSystemConfig from LaserPrinter, probably just not a Yamaha AVR.
[02/09/2024, 20:27:31] [yamaha-zone-tv] Adding TV Control for Main_Zone
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'AUDIO_RECEIVER')
    at YamahaAVRPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:271:104)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:489:14)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:704:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:730:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:604:18)
[02/09/2024, 20:27:36] [yamaha-zone-tv] Waited 5 seconds, stopping discovery.
[02/09/2024, 20:27:36] [yamaha-zone-tv] Discovery finished, found 0 Yamaha AVR devices.
```

### Configuration

```json
{
            "platform": "yamaha-zone-tv",
            "name": "yamaha-zone-tv",
            "discovery_timeout": 5,
            "radio_presets": false,
            "preset_num": false,
            "max_volume": 10,
            "disable_party_switch": true,
            "disable_main_power_switch": true,
            "zone_controllers_only_for": "Main",
            "_bridge": {
                "username": "0E:8E:A9:04:4C:31",
                "port": 42868
            }
        },
```

### Environment

-- | --
OS | Raspbian GNU/Linux Bullseye (11)
Homebridge | 2.0 Beta 15
NodeJS | v20.16.0

### Process Supervisor

hb-service

**Comment by Quickstep3** [comment]
See https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0 and https://github.com/homebridge/homebridge/issues/3661 for more info
